version: '3'

services:
  shared-expenses-mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: SE.2022*
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
volumes:
  data: